### ISSUE TITLE
png2tiles.py should behave more like png2sprites.py

### ISSUE THREAD

**Issue by pvmm** [reidrac/ubox-msx-lib#6]
png2sprites.py ignores the palette, but png2tiles.py doesn't. Even with `--no-colors` it will not allow images to be converted to tiles if the palette doesn't match the MSX palette, which I find a bit weird and inconsistent. Also, it could be useful if you want to import assets to the ubox library. May I tackle this issue?

**Comment by reidrac** [comment]
Is not inconsistent, you are comparing two tools that do very different things; let me explain the rationale behind it.

In png2sprites.py what we want is to define sprites, and those **are monochrome**, and the end result is monochrome frames to which you want to assign colours in your game. So we only care about the RGB value for **transparent**, and different colours will result in different frames. Very simple, but not well documented ;(

On the other hand, png2tiles.py needs to be aware of the palette and the MSX colour because the result is not monochrome and it must take into in account the MSX restrictions in order to encode the tiles following the "two colours per line" rule. The `--no-colors` refers *to the output*, in case you don't want the colour table (for example: you may want to generate it programmatically to save space; you can do that with text fonts).

So I would say there's no problem here, although we need to agree to which MSX palette are we going to use, and I decided to use an RGB approximation to the Toshiba palette, and that's it.

What you are pointing out here is something that I'm aware is missing: tools documentation. And I should tackle that when I have the time, meanwhile the CLI help and the example game (that comes with assets) I hope it will be enough.

I can start adding the structure to the docs and, after that, any help will be welcomed!

**Comment by reidrac** [comment]
Actually, I was not sure I wanted to document the tools further because those are helpers to make games but are not really necessary to use the libraries.

But if you think those tools are important to make games with the libs, they are open source already, so is just documenting them so they are easier to use.

**Comment by reidrac** [comment]
I've added a placeholder in ae19de1c2dcc160495fcffb198f9266cd52a36a5.

I'll start documenting the tools in `docs/tools.md`!
